#!/bin/bash

if [[ $(pwd) =~ ^(.*applied2).* ]]
then
    echo "in applied2"
    "${BASH_REMATCH[1]}/dev/containers/dev/into.sh" || redev
elif [[ $(pwd) =~ ^(.*mosaic-eng).* ]]
then
    echo "in mosaic-eng"
    "${BASH_REMATCH[1]}/docker/dev/into.sh" || redev
else
    echo "not in applied2 or mosaic-eng"
fi