#!/bin/bash

set -x

docker container prune -y

if [[ $(pwd) =~ ^(.*applied2).* ]]
then
    echo "in applied2: $(basename "$(pwd)")"
    "${BASH_REMATCH[1]}/dev/containers/dev/remove.sh" -name "$(basename "$(pwd)")"
    "${BASH_REMATCH[1]}/dev/containers/dev/start.sh" -name "$(basename "$(pwd)")"
    "${BASH_REMATCH[1]}/dev/containers/dev/into.sh" -name "$(basename "$(pwd)")"
elif [[ $(pwd) =~ ^(.*mosaic-eng).*$ ]]
then
    echo "in mosaic-eng repo: $(basename "$(pwd)")"
    "${BASH_REMATCH[1]}/docker/dev/remove.sh" -name "$(basename "$(pwd)")"

    if [ "$(basename "$(pwd)")" == "mosaic-eng" ]
    then
        "${BASH_REMATCH[1]}/docker/dev/start.sh" -name "$(basename "$(pwd)")"
    else
        "${BASH_REMATCH[1]}/docker/dev/start.sh" -name "$(basename "$(pwd)")" -no_mount_ports
    fi

    "${BASH_REMATCH[1]}/docker/dev/into.sh" -name "$(basename "$(pwd)")"
else
    echo "not in applied2 or mosaic-eng"
fi