#!/bin/bash

if [[ $(pwd) =~ ^(.*applied2).* ]]
then
    echo "in applied2"
    "${BASH_REMATCH[1]}/dev/containers/dev/remove.sh"
    "${BASH_REMATCH[1]}/dev/containers/dev/start.sh"
    "${BASH_REMATCH[1]}/dev/containers/dev/into.sh"
elif [[ $(pwd) =~ ^(.*mosaic-eng).* ]]
then
    echo "in mosaic-eng"
    "${BASH_REMATCH[1]}/docker/dev/remove.sh"
    "${BASH_REMATCH[1]}/docker/dev/start.sh"
    "${BASH_REMATCH[1]}/docker/dev/into.sh"
else
    echo "not in applied2 or mosaic-eng"
fi